<?php

namespace RevoSystems\SageLiveApi\SObjects;

use RevoSystems\SageLiveApi\SageResource;

class SageTransactionType extends SageResource {

    const RESOURCE_NAME = "s2cor__Sage_INV_Trade_Document_Type__c";
    protected $fields = [
        "s2cor__Account_Dimension__c"                   => [ "required" => false, "type" => "Lookup(Dimension)"     ],
        "s2cor__Account_Type_Filter_1__c"               => [ "required" => false, "type" => "Text(255)"             ],
        "s2cor__Account_Type_Filter_2__c"               => [ "required" => false, "type" => "Text(255)"             ],
        "s2cor__Account_Type_Filter_3__c"               => [ "required" => false, "type" => "Text(255)"             ],
        "s2cor__Account_Type_Filter_4__c"               => [ "required" => false, "type" => "Text(255)"             ],
        "s2cor__Active__c"                              => [ "required" => false, "type" => "Checkbox"              ],
        "s2cor__Allow_Convert_Repetition__c"            => [ "required" => false, "type" => "Picklist"              ],
        "s2cor__Allow_Negative_Amounts__c"              => [ "required" => false, "type" => "Checkbox"              ],
        "s2cor__Approval_Required__c"                   => [ "required" => false, "type" => "Checkbox"              ],
        "s2cor__Area__c"                                => [ "required" => false, "type" => "Picklist (Multi-Select)"],
        "s2cor__Available_in_Mobile__c"                 => [ "required" => false, "type" => "Checkbox"              ],
        "s2cor__Can_Be_Converted_To__c"                 => [ "required" => false, "type" => "Lookup(Transaction Type)"],
        "s2cor__Can_be_posted__c"                       => [ "required" => false, "type" => "Checkbox"              ],
        "s2cor__Can_Create_Jobs__c"                     => [ "required" => false, "type" => "Checkbox"              ],
        "s2cor__Classification__c"                      => [ "required" => false, "type" => "Picklist"              ],
        "s2cor__Company__c"                             => [ "required" => false, "type" => "Lookup(Company)"       ],
        "CreatedById"                                   => [ "required" => false, "type" => "Lookup(User)"          ],
        "s2cor__Default_Description__c"                 => [ "required" => false, "type" => "Text Area(255)"        ],
        "s2cor__Defaulted_Location__c"                  => [ "required" => false, "type" => "Lookup(Location)"      ],
        "s2cor__Default_Payment_Terms__c"               => [ "required" => false, "type" => "Lookup(Dimension Tag)" ],
        "s2cor__Default_PDF_Footer__c"                  => [ "required" => false, "type" => "Text Area(255)"        ],
        "s2cor__Default_Price_Book__c"                  => [ "required" => false, "type" => "Lookup(Price Book)"    ],
        "s2cor__Default_Tax_Code__c"                    => [ "required" => false, "type" => "Lookup(Tax Code)"      ],
        "s2cor__Default_Tax_Treatment__c"               => [ "required" => false, "type" => "Lookup(Tax Treatment)" ],
        "s2cor__Description__c"                         => [ "required" => false, "type" => "Long Text Area(32768)" ],
        "s2cor__Document_Number_Dimension__c"           => [ "required" => false, "type" => "Lookup(Dimension)"     ],
        "s2cor__Draft_Label__c"                         => [ "required" => false, "type" => "Text(100)"             ],
        "s2cor__Email_Template__c"                      => [ "required" => false, "type" => "Text(255)"             ],
        "s2cor__Job__c"                                 => [ "required" => false, "type" => "Lookup(Job)"           ],
        "s2cor__Recognition_Job__c"                     => [ "required" => false, "type" => "Lookup(Job)"           ],
        "s2cor__Journal_Type__c"                        => [ "required" => false, "type" => "Lookup(Journal Type)"  ],
        "s2cor__Recognition_Journal_Type__c"            => [ "required" => false, "type" => "Lookup(Journal Type)"  ],
        "LastModifiedById"                              => [ "required" => false, "type" => "Lookup(User)"          ],
        "s2cor__Legislation__c"                         => [ "required" => false, "type" => "Lookup(Legislation)"   ],
        "s2cor__Logo_Position__c"                       => [ "required" => false, "type" => "Picklist"              ],
        "Name"                                          => [ "required" => false, "type" => "Text(80)"              ],
        "s2cor__New_Attachment_on_Print__c"             => [ "required" => false, "type" => "Checkbox"              ],
        "OwnerId"                                       => [ "required" => false, "type" => "Lookup(User,Group)"    ],
        "s2cor__Pay_Now_Provider__c"                    => [ "required" => false, "type" => "Lookup(Feed)"          ],
        "s2cor__Payment_Journal_Type__c"                => [ "required" => false, "type" => "Lookup(Journal Type)"  ],
        "s2cor__Payment_Reference__c"                   => [ "required" => false, "type" => "Text(255)"             ],
        "s2cor__Payment_Terms_Dimension__c"             => [ "required" => false, "type" => "Lookup(Dimension)"     ],
        "s2cor__PDF_Template_Page__c"                   => [ "required" => false, "type" => "Text(255)"             ],
        "s2cor__Plural_Name__c"                         => [ "required" => false, "type" => "Text(100)"             ],
        "s2cor__Post_Recurrent_Documents__c"            => [ "required" => false, "type" => "Checkbox"              ],
        "s2cor__Decimal_Precision__c"                   => [ "required" => false, "type" => "Picklist"              ],
        "s2cor__Print_Outstanding_Amount__c"            => [ "required" => false, "type" => "Checkbox"              ],
        "s2cor__Product_Dimension__c"                   => [ "required" => false, "type" => "Lookup(Dimension)"     ],
        "s2cor__Decimal_Precision_Quantity__c"          => [ "required" => false, "type" => "Picklist"              ],
        "s2cor__Is_Recognition__c"                      => [ "required" => false, "type" => "Checkbox"              ],
        "s2cor__Reference_Description__c"               => [ "required" => false, "type" => "Text(100)"             ],
        "s2cor__Show_Company_Information__c"            => [ "required" => false, "type" => "Checkbox"              ],
        "s2cor__Stock_Layer__c"                         => [ "required" => false, "type" => "Picklist"              ],
        "s2cor__Stock_Transaction__c"                   => [ "required" => false, "type" => "Checkbox"              ],
        "s2cor__Stock_Type__c"                          => [ "required" => false, "type" => "Picklist"              ],
        "s2cor__Is_Scheduled__c"                        => [ "required" => false, "type" => "Checkbox"              ],
        "s2cor__Tax_Rate_Dimension__c"                  => [ "required" => false, "type" => "Lookup(Dimension)"     ],
        "s2cor__Template__c"                            => [ "required" => false, "type" => "Lookup(Template)"      ],
        "s2cor__Is_Transaction_Template__c"             => [ "required" => false, "type" => "Checkbox"              ],
        "s2cor__Treat_As__c"                            => [ "required" => false, "type" => "Picklist"              ],
        "s2cor__UID__c"                                 => [ "required" => false, "type" => "Text(128) (External ID) (Unique Case Sensitive)"],
        "s2cor__VF_Page__c"                             => [ "required" => false, "type" => "Text(255)"             ],
        "s2cor__Withholding_Dimension__c"               => [ "required" => false, "type" => "Lookup(Dimension)"     ],
    ];
}
